version: "2"

networks:
  voluets-net:
    driver: bridge

services:
  postgres:
    image: postgres:12
    restart: always
    container_name: voluets_postgres
    expose:
      - 5432
    volumes:
      - ~/voluets_postgres:/var/lib/postgresql/data
    env_file: ./Calculation/voluets_calculator/.postgres.env
    networks:
      - voluets-net

  voluets_calculator:
    build:
      context: ./Calculation/voluets_calculator/
      dockerfile: Dockerfile
    restart: always
    container_name: voluets_calculator
    expose:
      - 4000
    depends_on:
      - postgres
    env_file: ./Calculation/voluets_calculator/.voluets_calculator.env
    networks:
      - voluets-net

  voluets_api:
    build:
      context: ./Api/Voluets.API/
      dockerfile: Dockerfile
    restart: always
    container_name: voluets_api
    ports:
      - "80:80"
    depends_on:
      - postgres
      - voluets_calculator
    networks:
      - voluets-net
